AWSTemplateFormatVersion: '2010-09-09'


Parameters:
  GithubToken:
    Type: String
    Description: access token to github
    Default: xxxx # should be read from the main stack template parameter
  CloudmrServer:
    Type: String
    Description: "CLOUDMR_SERVER"
  MroServer:
    Type: String
    Description: "MRO_SERVER"
  ProfileServer:
    Type: String
    Description: "PROFILE_SERVER"
  TokenUrl:
    Type: String
    Description: "TOKEN_URL"
  ApiToken:
    Type: String
    Description: "API-TOKEN"



Resources:
  AmplifyConsoleServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - amplify.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: AmplifyConsoleServicePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'codebuild:StartBuild'
                  - 'codebuild:BatchGetBuilds'
                Resource: '*'
  MROFrontend:
    Type: AWS::Amplify::App
    Properties:
      AccessToken: !Ref GithubToken
      AutoBranchCreationConfig:
        EnableAutoBranchCreation: true
        EnableAutoBuild: true
        AutoBranchCreationPatterns:
          - "publish"
      CustomRules:
        - Source: "/websignin/"
          Status: "200"
          Target: "/index.html"
        - Source: "</^[^.]+$|\\.(?!(css|gif|ico|jpg|jpeg|js|png|txt|svg|woff|woff2|ttf|map|json|webp)$)([^.]+$)/>"
          Status: "200"
          Target: "/index.html"
      Description: "Your App Description Here"
      EnableBranchAutoDeletion: false
      Name: "MROptimum-Frontend-$RANDOM"
      Platform: "WEB"
      Repository: "https://github.com/cloudmrhub-com/MROptimum-frontend"
      Tags:
        - Key: "owner"
          Value: "cloudmrhub"
        - Key: "maintainer"
          Value: "YL6709"
        - Key: "project"
          Value: "mroptimum-v1"
        - Key: "team"
          Value: "cloudmrhub"
        - Key: "status"
          Value: "prod"
        - Key: "deletable"
          Value: "check"


  PublishBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt MROFrontend.AppId
      BranchName: "publish"
      EnableAutoBuild: true
      EnablePullRequestPreview: true

      BuildSpec: |
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - yarn install
            build:
              commands:
                - cat << EOF > src/env.ts
                - export const CLOUDMR_SERVER = '$CLOUDMR_SERVER';
                - export const MRO_SERVER = '$MRO_SERVER';
                - export const PROFILE_SERVER = '$PROFILE_SERVER';
                - export const API_TOKEN = '$API_TOKEN';
                - export const TOKEN_URL = '$TOKEN_URL';
                - EOF
                - yarn build
          artifacts:
            baseDirectory: build
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*
      Framework: "WEB"
      Stage: "PRODUCTION"
      EnvironmentVariables:
        - Name: "CLOUDMR_SERVER"
          Value: !Ref CloudmrServer
        - Name: "MRO_SERVER"
          Value: !Ref MroServer
        - Name: "PROFILE_SERVER"
          Value: !Ref ProfileServer
        - Name: "TOKEN_URL"
          Value: !Ref TokenUrl # REQUEST, POST {"type": (array or string)["mr optimum","upload",'tess'],"token":""}, RESULTS {"api-token":"dedddd"} you want to check if if the results
        - Name: "API_TOKEN"
          Value: !Ref ApiToken


Outputs:
  AmplifyAppDomain:
    Value: !Sub "${PublishBranch.BranchName}.${MROFrontend.DefaultDomain}"
