AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MROFrontend:
    Type: AWS::Amplify::App
    Properties:
      AccessToken: "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"
      AutoBranchCreationConfig:
        EnableAutoBranchCreation: true
        EnableAutoBuild: true
        AutoBranchCreationPatterns:
          - "publish"
      CustomRules:
        - Source: "/websignin/"
          Status: "200"
          Target: "/index.html"
        - Source: "</^[^.]+$|\\.(?!(css|gif|ico|jpg|jpeg|js|png|txt|svg|woff|woff2|ttf|map|json|webp)$)([^.]+$)/>"
          Status: "200"
          Target: "/index.html"
      Description: "Your App Description Here"
      EnableBranchAutoDeletion: false
      EnvironmentVariables:
        - Name: "CLOUDMR_SERVER"
          Value: "https://ewjjq013u0.execute-api.us-east-1.amazonaws.com"
        - Name: "MRO_SERVER"
          Value: "https://dplk0uo9d0.execute-api.us-east-1.amazonaws.com/Prod"
        - Name: "PROFILE_SERVER"
          Value: "https://qluq4mscci.execute-api.us-east-1.amazonaws.com/Prod"
      Name: "NYUMROptimumFrontend"
      Platform: "WEB"
      Repository: "https://github.com/cloudmrhub-com/MROptimum-frontend"
      Tags:
        - Key: "owner"
          Value: "cloudmrhub"
        - Key: "maintainer"
          Value: "yuelong"
        - Key: "project"
          Value: "mroptimum-v1"
        - Key: "team"
          Value: "cloudmrhub"
        - Key: "status"
          Value: "prod"
        - Key: "deletable"
          Value: "check"

  PublishBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt MROFrontend.AppId
      BranchName: "publish"
      EnableAutoBuild: true
      BuildSpec: |
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - yarn install
            build:
              commands:
                - cat << EOF > src/env.ts
                - export const CLOUDMR_SERVER = '$CLOUDMR_SERVER';
                - export const MRO_SERVER = '$MRO_SERVER';
                - export const PROFILE_SERVER = '$PROFILE_SERVER';
                - EOF
                - yarn build
          artifacts:
            baseDirectory: build
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*
      Framework: "WEB"
      Stage: "PRODUCTION"
      EnvironmentVariables:
        - Name: "API_ROOT"
          Value: "https://domain.com"
